<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 7" host="W7-GN-FC-286"><DocLocation><![CDATA[D:\Core18_4\Core2P-18.4\Test Script\KBYO2\E2E_KBYO2_BorrowerVesting_NBO]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[E2E_KBYO2_BorrowerVesting_NBO]]></DName>
<Res><![CDATA[Res3]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[MainAction]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:21]]></Time>
<TimeTick>1535102541</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\SmartClientCache\Apps\Ellie Mae\Encompass\Encompass.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\SmartClientCache\Apps\Ellie Mae\Encompass\Encompass.exe",1]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:21]]></Time>
<TimeTick>1535102541</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "C:\SmartClientCache\Apps\Ellie Mae\Encompass\Encompass.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ SwfWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:25]]></Time>
<TimeTick>1535102545</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" >
<Disp><![CDATA[[ SwfWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ SwfWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:27]]></Time>
<TimeTick>1535102547</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" >
<Disp><![CDATA[[ SwfWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ SwfWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:28]]></Time>
<TimeTick>1535102548</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" >
<Disp><![CDATA[[ SwfWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ SwfWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:29]]></Time>
<TimeTick>1535102549</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="19" >
<Disp><![CDATA[[ SwfWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ SwfWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:30]]></Time>
<TimeTick>1535102550</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="21" >
<Disp><![CDATA[[ SwfWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ SwfWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:32]]></Time>
<TimeTick>1535102552</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="23" >
<Disp><![CDATA[[ SwfWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ SwfWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:33]]></Time>
<TimeTick>1535102553</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="25" >
<Disp><![CDATA[[ SwfWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ SwfWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:34]]></Time>
<TimeTick>1535102554</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="27" >
<Disp><![CDATA[[ SwfWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ Encompass Log In ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:36]]></Time>
<TimeTick>1535102556</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="28" >
<Disp><![CDATA[[ Encompass Log In ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ Encompass Log In ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 120000]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:36]]></Time>
<TimeTick>1535102556</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="30" >
<Disp><![CDATA[[ Encompass Log In ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ Encompass Log In ].Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:37]]></Time>
<TimeTick>1535102557</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="32" >
<Disp><![CDATA[[ Encompass Log In ].Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ loginNameBox ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:37]]></Time>
<TimeTick>1535102557</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="34" >
<Disp><![CDATA[[ loginNameBox ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ passwordBox ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["password"]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:37]]></Time>
<TimeTick>1535102557</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="36" >
<Disp><![CDATA[[ passwordBox ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Edit ].SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["http://eq1veabe31064.dco.elmae/encompass$BE11205010"]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:39]]></Time>
<TimeTick>1535102559</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="38" >
<Disp><![CDATA[[ Edit ].SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ Log In ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 14:52:39]]></Time>
<TimeTick>1535102559</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="40" >
<Disp><![CDATA[[ Log In ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ Dialog ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:03]]></Time>
<TimeTick>1535102583</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="45" >
<Disp><![CDATA[[ Dialog ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:04]]></Time>
<TimeTick>1535102584</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="46" >
<Disp><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 120000]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:04]]></Time>
<TimeTick>1535102584</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="48" >
<Disp><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].Maximize]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:04]]></Time>
<TimeTick>1535102584</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="50" >
<Disp><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].Maximize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:06]]></Time>
<TimeTick>1535102586</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="51" >
<Disp><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj ><![CDATA[Login to Encompass SmartClient]]></Obj>
<Details ><![CDATA[Logged in as admin. Build 18.4.0.0 . Server: http://eq1veabe31064.dco.elmae/encompass$BE11205010]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:06]]></Time>
<TimeTick>1535102586</TimeTick>
<NodeArgs eType="User" icon="11" nRep="52" status="Passed" >
<Disp><![CDATA[Login to Encompass SmartClient]]></Disp>
</NodeArgs>
</Step>
<Action rID="T28">
<AName><![CDATA[CM_LinkedLoan]]></AName>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ tabControl ].ItemsCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:16]]></Time>
<TimeTick>1535102596</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="55" >
<Disp><![CDATA[[ tabControl ].ItemsCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ tabControl ].GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:16]]></Time>
<TimeTick>1535102596</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="57" >
<Disp><![CDATA[[ tabControl ].GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ tabControl ].GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:17]]></Time>
<TimeTick>1535102597</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="59" >
<Disp><![CDATA[[ tabControl ].GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ tabControl ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Pipeline"]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:17]]></Time>
<TimeTick>1535102597</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="61" >
<Disp><![CDATA[[ tabControl ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ cboFolder ].GetContent]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:29]]></Time>
<TimeTick>1535102609</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="63" >
<Disp><![CDATA[[ cboFolder ].GetContent]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ cboFolder ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Automation"]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:29]]></Time>
<TimeTick>1535102609</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="65" >
<Disp><![CDATA[[ cboFolder ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ btnNew ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:39]]></Time>
<TimeTick>1535102619</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="66" >
<Disp><![CDATA[[ btnNew ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ btnNew ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:39]]></Time>
<TimeTick>1535102619</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="68" >
<Disp><![CDATA[[ btnNew ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ New Blank Loan ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:41]]></Time>
<TimeTick>1535102621</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="69" >
<Disp><![CDATA[[ New Blank Loan ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ New Blank Loan ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 30000]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:41]]></Time>
<TimeTick>1535102621</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="71" >
<Disp><![CDATA[[ New Blank Loan ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ New Blank Loan ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:42]]></Time>
<TimeTick>1535102622</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="72" >
<Disp><![CDATA[[ New Blank Loan ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ New Blank Loan ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", True, True, 70000]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:42]]></Time>
<TimeTick>1535102622</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="74" >
<Disp><![CDATA[[ New Blank Loan ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ New Blank Loan ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 14:53:42]]></Time>
<TimeTick>1535102622</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="76" >
<Disp><![CDATA[[ New Blank Loan ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ Dialog ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:54:13]]></Time>
<TimeTick>1535102653</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="78" >
<Disp><![CDATA[[ Dialog ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ Dialog ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:54:44]]></Time>
<TimeTick>1535102684</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="80" >
<Disp><![CDATA[[ Dialog ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ toolsFormsTabControl ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 14:54:45]]></Time>
<TimeTick>1535102685</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="81" >
<Disp><![CDATA[[ toolsFormsTabControl ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj ><![CDATA[Add New Loan]]></Obj>
<Details ><![CDATA[Created new blank Loan]]></Details>
<Time><![CDATA[8/24/2018 - 14:54:45]]></Time>
<TimeTick>1535102685</TimeTick>
<NodeArgs eType="User" icon="11" nRep="82" status="Passed" >
<Disp><![CDATA[Add New Loan]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ toolsFormsTabControl ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 14:54:50]]></Time>
<TimeTick>1535102690</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="83" >
<Disp><![CDATA[[ toolsFormsTabControl ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ toolsFormsTabControl ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Forms"]]></Details>
<Time><![CDATA[8/24/2018 - 14:54:50]]></Time>
<TimeTick>1535102690</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="85" >
<Disp><![CDATA[[ toolsFormsTabControl ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ toolsFormsTabControl ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 14:54:50]]></Time>
<TimeTick>1535102690</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="86" >
<Disp><![CDATA[[ toolsFormsTabControl ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ toolsFormsTabControl ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Forms"]]></Details>
<Time><![CDATA[8/24/2018 - 14:54:50]]></Time>
<TimeTick>1535102690</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="88" >
<Disp><![CDATA[[ toolsFormsTabControl ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ Show in Alpha Order ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 14:54:52]]></Time>
<TimeTick>1535102692</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="89" >
<Disp><![CDATA[[ Show in Alpha Order ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ Show in Alpha Order ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 14:54:52]]></Time>
<TimeTick>1535102692</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="90" >
<Disp><![CDATA[[ Show in Alpha Order ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ Show in Alpha Order ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", True, True, 70000]]></Details>
<Time><![CDATA[8/24/2018 - 14:54:52]]></Time>
<TimeTick>1535102692</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="92" >
<Disp><![CDATA[[ Show in Alpha Order ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[[ Show in Alpha Order ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[8/24/2018 - 14:54:52]]></Time>
<TimeTick>1535102692</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="94" >
<Disp><![CDATA[[ Show in Alpha Order ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ Show All ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 14:54:53]]></Time>
<TimeTick>1535102693</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="95" >
<Disp><![CDATA[[ Show All ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ Show All ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["enabled", True, True, 70000]]></Details>
<Time><![CDATA[8/24/2018 - 14:54:53]]></Time>
<TimeTick>1535102693</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="97" >
<Disp><![CDATA[[ Show All ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ Show All ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[8/24/2018 - 14:54:53]]></Time>
<TimeTick>1535102693</TimeTick>
<NodeArgs eType="Replay" icon="15" nRep="99" >
<Disp><![CDATA[[ Show All ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[[ Borrower Summary - Origination ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:01]]></Time>
<TimeTick>1535102701</TimeTick>
<NodeArgs eType="Replay" icon="16" nRep="100" >
<Disp><![CDATA[[ Borrower Summary - Origination ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:13]]></Time>
<TimeTick>1535102713</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="104" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:15]]></Time>
<TimeTick>1535102715</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="108" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:16]]></Time>
<TimeTick>1535102716</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="112" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:19]]></Time>
<TimeTick>1535102719</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="116" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:20]]></Time>
<TimeTick>1535102720</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="120" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:22]]></Time>
<TimeTick>1535102722</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="124" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:24]]></Time>
<TimeTick>1535102724</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="128" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:25]]></Time>
<TimeTick>1535102725</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="132" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:27]]></Time>
<TimeTick>1535102727</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="136" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:29]]></Time>
<TimeTick>1535102729</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="140" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:30]]></Time>
<TimeTick>1535102730</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="144" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:32]]></Time>
<TimeTick>1535102732</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="148" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:34]]></Time>
<TimeTick>1535102734</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="152" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:36]]></Time>
<TimeTick>1535102736</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="156" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:38]]></Time>
<TimeTick>1535102738</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="160" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T73">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:40]]></Time>
<TimeTick>1535102740</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="164" >
<Disp><![CDATA[[ WebEdit ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T74">
<Obj plainTxt="False" ><![CDATA[[ WebEdit ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 14:55:42]]></Time>
<TimeTick>1535102742</TimeTick>
<NodeArgs eType="Replay" icon="17" nRep="168" >