<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.02" os="Windows 7" host="W7-GN-FC-286"><DocLocation><![CDATA[D:\Core18_4\Core2P-18.4\Test Script\KBYO2\E2E_KBYO2_BorrowerVesting_NBO]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[E2E_KBYO2_BorrowerVesting_NBO]]></DName>
<Res><![CDATA[Res4]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[MainAction]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[8/24/2018 - 16:12:37]]></Time>
<TimeTick>1535107357</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "C:\SmartClientCache\Apps\Ellie Mae\Encompass\Encompass.exe",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "C:\SmartClientCache\Apps\Ellie Mae\Encompass\Encompass.exe",1]]></Details>
<Time><![CDATA[8/24/2018 - 16:12:37]]></Time>
<TimeTick>1535107357</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" >
<Disp><![CDATA[Run "C:\SmartClientCache\Apps\Ellie Mae\Encompass\Encompass.exe",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[[ SwfWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:12:41]]></Time>
<TimeTick>1535107361</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" >
<Disp><![CDATA[[ SwfWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[[ SwfWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:12:43]]></Time>
<TimeTick>1535107363</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="15" >
<Disp><![CDATA[[ SwfWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[[ SwfWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:12:46]]></Time>
<TimeTick>1535107366</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="17" >
<Disp><![CDATA[[ SwfWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[[ SwfWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:12:47]]></Time>
<TimeTick>1535107367</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="19" >
<Disp><![CDATA[[ SwfWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[[ SwfWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:12:49]]></Time>
<TimeTick>1535107369</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="21" >
<Disp><![CDATA[[ SwfWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[[ SwfWindow ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:12:50]]></Time>
<TimeTick>1535107370</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="23" >
<Disp><![CDATA[[ SwfWindow ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[[ Encompass Log In ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 16:12:51]]></Time>
<TimeTick>1535107371</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="24" >
<Disp><![CDATA[[ Encompass Log In ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[[ Encompass Log In ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 120000]]></Details>
<Time><![CDATA[8/24/2018 - 16:12:51]]></Time>
<TimeTick>1535107371</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="26" >
<Disp><![CDATA[[ Encompass Log In ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[[ Encompass Log In ].Activate]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 16:12:51]]></Time>
<TimeTick>1535107371</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="28" >
<Disp><![CDATA[[ Encompass Log In ].Activate]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[[ loginNameBox ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["admin"]]></Details>
<Time><![CDATA[8/24/2018 - 16:12:52]]></Time>
<TimeTick>1535107372</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="30" >
<Disp><![CDATA[[ loginNameBox ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[[ passwordBox ].Set]]></Obj>
<Details plainTxt="False" ><![CDATA["password"]]></Details>
<Time><![CDATA[8/24/2018 - 16:12:52]]></Time>
<TimeTick>1535107372</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="32" >
<Disp><![CDATA[[ passwordBox ].Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[[ Edit ].SetText]]></Obj>
<Details plainTxt="False" ><![CDATA["http://eq1veabe31064.dco.elmae/encompass$BE11205010"]]></Details>
<Time><![CDATA[8/24/2018 - 16:12:52]]></Time>
<TimeTick>1535107372</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="34" >
<Disp><![CDATA[[ Edit ].SetText]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[[ Log In ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 16:12:53]]></Time>
<TimeTick>1535107373</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="36" >
<Disp><![CDATA[[ Log In ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[[ Dialog ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:13:16]]></Time>
<TimeTick>1535107396</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="41" >
<Disp><![CDATA[[ Dialog ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 16:13:17]]></Time>
<TimeTick>1535107397</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="42" >
<Disp><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 120000]]></Details>
<Time><![CDATA[8/24/2018 - 16:13:17]]></Time>
<TimeTick>1535107397</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="44" >
<Disp><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].Maximize]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 16:13:17]]></Time>
<TimeTick>1535107397</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="46" >
<Disp><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].Maximize]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 16:13:35]]></Time>
<TimeTick>1535107415</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="47" >
<Disp><![CDATA[[ Encompass - Build 18.4.0.0 - http://eq1veabe31064.dco.elmae/encompass$BE11205010 - admin - 3011205011 ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[Login to Encompass SmartClient]]></Obj>
<Details ><![CDATA[Logged in as admin. Build 18.4.0.0 . Server: http://eq1veabe31064.dco.elmae/encompass$BE11205010]]></Details>
<Time><![CDATA[8/24/2018 - 16:13:35]]></Time>
<TimeTick>1535107415</TimeTick>
<NodeArgs eType="User" icon="11" nRep="48" status="Passed" >
<Disp><![CDATA[Login to Encompass SmartClient]]></Disp>
</NodeArgs>
</Step>
<Action rID="T26">
<AName><![CDATA[CM_LinkedLoan]]></AName>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[[ tabControl ].ItemsCount]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 16:13:46]]></Time>
<TimeTick>1535107426</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="51" >
<Disp><![CDATA[[ tabControl ].ItemsCount]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[[ tabControl ].GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 16:13:46]]></Time>
<TimeTick>1535107426</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="53" >
<Disp><![CDATA[[ tabControl ].GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[[ tabControl ].GetItem]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 16:13:47]]></Time>
<TimeTick>1535107427</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="55" >
<Disp><![CDATA[[ tabControl ].GetItem]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[[ tabControl ].Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Pipeline"]]></Details>
<Time><![CDATA[8/24/2018 - 16:13:49]]></Time>
<TimeTick>1535107429</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="57" >
<Disp><![CDATA[[ tabControl ].Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[[ btnNew ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:07]]></Time>
<TimeTick>1535107447</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="58" >
<Disp><![CDATA[[ btnNew ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[[ btnNew ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:07]]></Time>
<TimeTick>1535107447</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="60" status="Warning" >
<Disp><![CDATA[[ btnNew ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[[ btnNew ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object not visible]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:07]]></Time>
<TimeTick>1535107447</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[[ btnNew ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>swfname = btnNew<br>Index = 0<br>]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:07]]></Time>
<TimeTick>1535107447</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="62" status="Warning" nType="Description" >
<Disp><![CDATA[[ btnNew ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="13" nRep="61" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ btnNew ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[[ btnNew ].Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:07]]></Time>
<TimeTick>1535107447</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="64" status="Warning" >
<Disp><![CDATA[[ btnNew ].Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[[ btnNew ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object not visible]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:07]]></Time>
<TimeTick>1535107447</TimeTick>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[[ btnNew ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>swfname = btnNew<br>Index = 0<br>]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:07]]></Time>
<TimeTick>1535107447</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="66" status="Warning" nType="Description" >
<Disp><![CDATA[[ btnNew ]]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="13" nRep="65" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ btnNew ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:10]]></Time>
<TimeTick>1535107450</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="72" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:12]]></Time>
<TimeTick>1535107452</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="78" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:16]]></Time>
<TimeTick>1535107456</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="84" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:19]]></Time>
<TimeTick>1535107459</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="90" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:21]]></Time>
<TimeTick>1535107461</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="96" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:23]]></Time>
<TimeTick>1535107463</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="102" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:25]]></Time>
<TimeTick>1535107465</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="108" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:28]]></Time>
<TimeTick>1535107468</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="114" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:31]]></Time>
<TimeTick>1535107471</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="120" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:33]]></Time>
<TimeTick>1535107473</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="126" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:36]]></Time>
<TimeTick>1535107476</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="132" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:39]]></Time>
<TimeTick>1535107479</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="138" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:14:41]]></Time>
<TimeTick>1535107481</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="144" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].GetROProperty "swfname"]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 16:15:24]]></Time>
<TimeTick>1535107524</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="156" status="Warning" >
<Disp><![CDATA[[ SwfButton ].GetROProperty "swfname"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "[ SwfButton ]" object's parent "[ SwfWindow ]" (class SwfWindow). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[8/24/2018 - 16:15:24]]></Time>
<TimeTick>1535107524</TimeTick>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = New Loan<br>Index = 0<br>]]></Details>
<Time><![CDATA[8/24/2018 - 16:15:24]]></Time>
<TimeTick>1535107524</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="158" status="Warning" nType="Parent description" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="157" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ SwfButton ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, 30000]]></Details>
<Time><![CDATA[8/24/2018 - 16:16:10]]></Time>
<TimeTick>1535107570</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="170" status="Warning" >
<Disp><![CDATA[[ SwfButton ].WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].GetROProperty "swfname"]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[8/24/2018 - 16:16:56]]></Time>
<TimeTick>1535107616</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="182" status="Warning" >
<Disp><![CDATA[[ SwfButton ].GetROProperty "swfname"]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ]]]></Obj>
<Details plainTxt="False" ><![CDATA[Cannot find the "[ SwfButton ]" object's parent "[ SwfWindow ]" (class SwfWindow). Verify that parent properties match an object currently displayed in your application.]]></Details>
<Time><![CDATA[8/24/2018 - 16:16:56]]></Time>
<TimeTick>1535107616</TimeTick>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>Text = New Loan<br>Index = 0<br>]]></Details>
<Time><![CDATA[8/24/2018 - 16:16:56]]></Time>
<TimeTick>1535107616</TimeTick>
<NodeArgs eType="Replay" icon="14" nRep="184" status="Warning" nType="Parent description" >
<Disp><![CDATA[]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="9" nRep="183" status="Failed" nType="Run Error" >
<Disp><![CDATA[[ SwfButton ]]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:16:59]]></Time>
<TimeTick>1535107619</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="190" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:17:03]]></Time>
<TimeTick>1535107623</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="196" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T60">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:17:05]]></Time>
<TimeTick>1535107625</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="202" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T61">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:17:09]]></Time>
<TimeTick>1535107629</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="208" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T62">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:17:11]]></Time>
<TimeTick>1535107631</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="214" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T63">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:17:13]]></Time>
<TimeTick>1535107633</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="220" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T64">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:17:17]]></Time>
<TimeTick>1535107637</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="226" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T65">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:17:19]]></Time>
<TimeTick>1535107639</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="232" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T66">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:17:21]]></Time>
<TimeTick>1535107641</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="238" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T67">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:17:24]]></Time>
<TimeTick>1535107644</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="244" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T68">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:17:26]]></Time>
<TimeTick>1535107646</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="250" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T69">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:17:29]]></Time>
<TimeTick>1535107649</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="256" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T70">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:17:32]]></Time>
<TimeTick>1535107652</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="262" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T71">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:17:36]]></Time>
<TimeTick>1535107656</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="268" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T72">
<Obj plainTxt="False" ><![CDATA[[ SwfButton ].Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object does not exist"]]></Details>
<Time><![CDATA[8/24/2018 - 16:17:38]]></Time>
<TimeTick>1535107658</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="274" >
<Disp><![CDATA[[ SwfButton ].Exist]]></Disp>
</NodeArgs>
</Step>